/* DO NOT EDIT THIS FILE - it is machine generated */
/*
   Author: Rupert Smith
   Licence: This work is licensed under the Creative Commons Attribution License.
          View this license at http://creativecommons.org/about/licenses/

*/
#include <jni.h>
/* Header for class common_UartCode */

#ifndef _Included_common_UartCode
#define _Included_common_UartCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_UartCode
 * Method:    setControlPanelIntensity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_common_UartCode_setControlPanelIntensity
  (JNIEnv *, jobject, jint);

/*
 * Class:     common_UartCode
 * Method:    setControlPanelPageLoad
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_common_UartCode_setControlPanelPageLoad
  (JNIEnv *, jobject);

/*
 * Class:     common_UartCode
 * Method:    setControlPanelPageIntensity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_common_UartCode_setControlPanelPageIntensity
  (JNIEnv *, jobject, jint);

/*
 * Class:     common_UartCode
 * Method:    getControlPanelIntensity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_common_UartCode_getControlPanelIntensity
  (JNIEnv *, jobject);

/*
 * Class:     common_UartCode
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_common_UartCode_main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
