/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UartCode */

#ifndef _Included_UartCode
#define _Included_UartCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UartCode
 * Method:    getControlPanelIntensity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UartCode_getControlPanelIntensity
  (JNIEnv *, jobject);

/*
 * Class:     UartCode
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_UartCode_main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
